[[!comment format=mdwn
 username="jkniiv"
 avatar="http://cdn.libravatar.org/avatar/05fd8b33af7183342153e8013aa3713d"
 subject="my report was actually a User Failure on my part"
 date="2023-12-19T23:02:15Z"
 content="""
Uh-oh, after adding the option `--test-debug` to the `test` subcommand I got a lead on
the real culprit and it wasn't git-annex but libmagic:

[[!format sh \"\"\"
[...snip...]
ok
[2023-12-19 22:52:17.5370274] (Utility.Process) process [21636] done ExitSuccess
[2023-12-19 22:52:17.5460328] (Utility.Process) process [10460] read: git [\"--git-dir=.git\",\"--work-tree=.\",\"--literal-p
athspecs\",\"-c\",\"annex.debug=true\",\"ls-files\",\"-z\",\"--modified\",\"--\",\"foo\"]
[2023-12-19 22:52:17.5970346] (Utility.Process) process [10460] done ExitSuccess
[2023-12-19 22:52:17.6030281] (Utility.Process) process [9208] read: git [\"--git-dir=.git\",\"--work-tree=.\",\"--literal-pa
thspecs\",\"-c\",\"annex.debug=true\",\"diff\",\"--name-only\",\"--diff-filter=T\",\"-z\",\"--cached\",\"--\",\"foo\"]
[2023-12-19 22:52:17.6550242] (Utility.Process) process [9208] done ExitSuccess
(recording state in git...)
[2023-12-19 22:52:17.6650254] (Utility.Process) process [24064] feed: git [\"--git-dir=.git\",\"--work-tree=.\",\"--literal-p
athspecs\",\"-c\",\"annex.debug=true\",\"update-index\",\"-z\",\"--index-info\"]
[2023-12-19 22:52:17.7090277] (Utility.Process) process [24064] done ExitSuccess
[2023-12-19 22:52:17.7240248] (Utility.Process) process [22248] feed: git [\"--git-dir=.git\",\"--work-tree=.\",\"--literal-p
athspecs\",\"-c\",\"annex.debug=true\",\"update-index\",\"-z\",\"--index-info\"]
[2023-12-19 22:52:17.7700259] (Utility.Process) process [22248] done ExitSuccess
[2023-12-19 22:52:17.7780282] (Utility.Process) process [23188] read: git [\"--git-dir=.git\",\"--work-tree=.\",\"--literal-p
athspecs\",\"-c\",\"annex.debug=true\",\"show-ref\",\"--hash\",\"refs/heads/git-annex\"]
[2023-12-19 22:52:17.8270228] (Utility.Process) process [23188] done ExitSuccess
[2023-12-19 22:52:17.8340274] (Utility.Process) process [17648] feed: git [\"--git-dir=.git\",\"--work-tree=.\",\"--literal-p
athspecs\",\"-c\",\"annex.debug=true\",\"update-index\",\"-z\",\"--index-info\"]
[2023-12-19 22:52:17.8420331] (Utility.Process) process [21928] read: git [\"--git-dir=.git\",\"--work-tree=.\",\"--literal-p
athspecs\",\"-c\",\"annex.debug=true\",\"diff-index\",\"--raw\",\"-z\",\"-r\",\"--no-renames\",\"-l0\",\"--cached\",\"refs/heads/git-annex\",
\"--\"]
[2023-12-19 22:52:17.8980416] (Utility.Process) process [21928] done ExitSuccess
[2023-12-19 22:52:17.9060216] (Utility.Process) process [17648] done ExitSuccess
[2023-12-19 22:52:17.920024] (Utility.Process) process [18680] read: git [\"--git-dir=.git\",\"--work-tree=.\",\"--literal-pa
thspecs\",\"-c\",\"annex.debug=true\",\"write-tree\"]
[2023-12-19 22:52:17.982027] (Utility.Process) process [18680] done ExitSuccess
[2023-12-19 22:52:17.9890276] (Utility.Process) process [10892] chat: git [\"--git-dir=.git\",\"--work-tree=.\",\"--literal-p
athspecs\",\"-c\",\"annex.debug=true\",\"commit-tree\",\"bb68ce15d91f27eec51749b9481ede5cc6bcd190\",\"--no-gpg-sign\",\"-p\",\"refs/he
ads/git-annex\"]
[2023-12-19 22:52:18.0490233] (Utility.Process) process [10892] done ExitSuccess
[2023-12-19 22:52:18.0570304] (Utility.Process) process [6552] call: git [\"--git-dir=.git\",\"--work-tree=.\",\"--literal-pa
thspecs\",\"-c\",\"annex.debug=true\",\"update-ref\",\"refs/heads/git-annex\",\"71b9bb13e4244bd2233de7ca7cf7fc01011f1e62\"]
[2023-12-19 22:52:18.1170343] (Utility.Process) process [6552] done ExitSuccess
[2023-12-19 22:52:18.1300416] (Utility.Process) process [10116] done ExitSuccess
[2023-12-19 22:52:18.1350241] (Utility.Process) process [20976] done ExitSuccess
[2023-12-19 22:52:18.1400231] (Utility.Process) process [9880] done ExitSuccess
[2023-12-19 22:52:18.1450249] (Utility.Process) process [872] done ExitSuccess
C:\Users\jkniiv\AppData\Local/.magic/magic.mgc, 1: Warning: offset `∟♦▲FAIL (2.36s)
        .\\Test\\Framework.hs:83:
        add with SHA1 failed with unexpected exit code
        Use -p '(/Init Tests.add/||/Init Tests/)&&/add/' to rerun this test only.

1 out of 2 tests failed (8.86s)
git-annex: thread blocked indefinitely in an STM transaction

\"\"\"]]

So the real error turned out to be a user failure of mine: libmagic (or the msys2 package `mingw-w64-x86_64-file`)
had a recent update and the new library didn't like my previous magic database located in the fallback location
`%localappdata%\.magic\magic.mgc`. By copying the msys2 file `/mingw64/share/misc/magic.mgc` to the aforementioned
location, the whole issue cleared itself and this report became moot.


"""]]
